// <auto-generated />
using System;
using ERPAPP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERPAPP.Migrations
{
    [DbContext(typeof(ErpdbContext))]
    [Migration("20251018124513_Authority")]
    partial class Authority
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERPAPP.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("money");

                    b.HasKey("AccountId")
                        .HasName("PK__Accounts__349DA5A6019313FA");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("ERPAPP.Models.Budget", b =>
                {
                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int?>("其他")
                        .HasColumnType("int");

                    b.Property<int?>("大型器具")
                        .HasColumnType("int");

                    b.Property<int?>("娛樂")
                        .HasColumnType("int");

                    b.Property<int?>("學習深造")
                        .HasColumnType("int");

                    b.Property<int?>("日常用品")
                        .HasColumnType("int");

                    b.Property<int?>("服飾")
                        .HasColumnType("int");

                    b.Property<int?>("汽車")
                        .HasColumnType("int");

                    b.Property<int?>("盈餘")
                        .HasColumnType("int");

                    b.Property<int?>("總開銷")
                        .HasColumnType("int");

                    b.Property<int?>("總預算")
                        .HasColumnType("int");

                    b.Property<int?>("美容美髮")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("輸入日期")
                        .HasColumnType("date");

                    b.Property<int?>("醫療保健")
                        .HasColumnType("int");

                    b.Property<int?>("飲食")
                        .HasColumnType("int");

                    b.ToTable("budget", (string)null);
                });

            modelBuilder.Entity("ERPAPP.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A0B16F69806");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ERPAPP.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Account = "Boss",
                            DepartmentId = 1,
                            Name = "翰陞",
                            Password = "123"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Account = "Manager",
                            DepartmentId = 2,
                            Name = "林主管",
                            Password = "123"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Account = "Visiter",
                            DepartmentId = 3,
                            Name = "黃大壯",
                            Password = "123"
                        });
                });

            modelBuilder.Entity("ERPAPP.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MemberId")
                        .HasName("PK__Members__0CF04B1815F7BEB1");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("ERPAPP.Models.Property", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("可用餘額")
                        .HasColumnType("int");

                    b.Property<int>("學費")
                        .HasColumnType("int");

                    b.Property<int>("當月收入")
                        .HasColumnType("int");

                    b.Property<int>("總財產")
                        .HasColumnType("int");

                    b.Property<DateOnly>("輸入日期")
                        .HasColumnType("date");

                    b.Property<int>("預算金")
                        .HasColumnType("int");

                    b.ToTable("Property", (string)null);
                });

            modelBuilder.Entity("ERPAPP.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            EmployeeId = 1,
                            Name = "Select"
                        },
                        new
                        {
                            RoleId = 2,
                            EmployeeId = 1,
                            Name = "Edit"
                        },
                        new
                        {
                            RoleId = 3,
                            EmployeeId = 2,
                            Name = "Select"
                        });
                });

            modelBuilder.Entity("ERPAPP.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("Member")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransactionType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id")
                        .HasName("PK__Transact__3214EC07D8814338");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
