// <auto-generated />
using System;
using ERPAPP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ERPAPP.Migrations
{
    [DbContext(typeof(ErpdbContext))]
    [Migration("20251213061838_InitialPostgresMigration")]
    partial class InitialPostgresMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ERPAPP.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("money");

                    b.HasKey("AccountId")
                        .HasName("PK__Accounts__349DA5A6019313FA");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("ERPAPP.Models.Budget", b =>
                {
                    b.Property<int?>("Articles")
                        .HasColumnType("integer");

                    b.Property<int?>("Car")
                        .HasColumnType("integer");

                    b.Property<int?>("Cloth")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int?>("Expenditure")
                        .HasColumnType("integer");

                    b.Property<int?>("Food")
                        .HasColumnType("integer");

                    b.Property<int?>("Fun")
                        .HasColumnType("integer");

                    b.Property<int?>("Furniture")
                        .HasColumnType("integer");

                    b.Property<int?>("Gete")
                        .HasColumnType("integer");

                    b.Property<int?>("Hair")
                        .HasColumnType("integer");

                    b.Property<int?>("Health")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Inputdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Other")
                        .HasColumnType("integer");

                    b.Property<int?>("Study")
                        .HasColumnType("integer");

                    b.Property<int?>("Total")
                        .HasColumnType("integer");

                    b.ToTable("budget", (string)null);
                });

            modelBuilder.Entity("ERPAPP.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A0B16F69806");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ERPAPP.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("EmployeeId")
                        .HasName("PK_Employees_EmployeeId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("ERPAPP.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MemberId"));

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MemberId")
                        .HasName("PK__Members__0CF04B1815F7BEB1");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("ERPAPP.Models.Property", b =>
                {
                    b.Property<int?>("Budget")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<DateTime>("Inputdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Own")
                        .HasColumnType("integer");

                    b.Property<int?>("Sparemoney")
                        .HasColumnType("integer");

                    b.Property<int?>("Totalproperty")
                        .HasColumnType("integer");

                    b.Property<int?>("Tuitionfee")
                        .HasColumnType("integer");

                    b.ToTable("Property", (string)null);
                });

            modelBuilder.Entity("ERPAPP.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoleId")
                        .HasName("PK_Role_RoleId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("ERPAPP.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Member")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TransactionType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id")
                        .HasName("PK__Transact__3214EC07D8814338");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
